module.exports = {
    SETTINGS_WINDOW_LAUNCH: 'SETTINGS_WINDOW_LAUNCH',
    SETTINGS_WINDOW_SETTING: 'SETTINGS_WINDOW_SETTING',

    UPDATER_STATE_AUTO: 'UPDATER_STATE_AUTO',
    UPDATER_STATE_MANUAL: 'UPDATER_STATE_MANUAL'
}
