module.exports = {

    APP_EXIT: 'APP_EXIT',
    OPEN_LOGS: 'OPEN_LOGS',

    SETTINGS_WINDOW_LAUNCH: 'SETTINGS_WINDOW_LAUNCH',
    SETTINGS_WINDOW_SETTING: 'SETTINGS_WINDOW_SETTING',

    UPDATER_STATE_AUTO: 'UPDATER_STATE_AUTO',
    UPDATER_STATE_MANUAL: 'UPDATER_STATE_MANUAL',

    GO_DATA_LAUNCH_ERROR: 'GO_DATA_LAUNCH_ERROR',
    GO_DATA_KILL_ERROR: 'GO_DATA_KILL_ERROR',
    GO_DATA_BACKUP_ERROR: 'GO_DATA_BACKUP_ERROR'
}
