name: Build Installer

on:
  workflow_dispatch:
    inputs:
      Platform:
        description: 'Select platform you want to build for.'
        required: true
        default: 'linux'
        type: choice
        options:
        - linux
        - windows
        - macos
      APIBranchName: 
        description: 'Set the API branch to use for the build.'
        required: true
        default: 'master'
      FrontendBranchName: 
        description: 'Set the frontend branch to use for the build.'
        required: true
        default: 'master'
      OutputPath:
        description: 'Select the output path'
        required: true
        default: 'WHO'
        type: choice
        options:
        - WHO-Internal
        - WHO
      InternalBuild:
        description: 'Internal Build'
        required: false
        default: false
        type: boolean
      VersionNumber: 
        description: 'Set build version number.'
        required: true
        default: '2.x.x'

jobs:
  build_linux: 
    if: ${{ inputs.Platform }} == 'linux'
    uses: ./.github/workflows/build-linux-installer.yml
    with: 
      api-branch-name: ${{ inputs.APIBranchName }}
      frontend-branch-name: ${{ inputs.FrontBranchName }}
      output-path: ${{ inputs.OutputPath }}
      internal-build: ${{ inputs.InternalBuild }}
      version-number: ${{ inputs.VersionNumber }}
  
  build_windows:
    if: ${{ inputs.Platform }} == 'windows'
    uses: ./.github/workflows/build-windows-installer.yml
    with: 
      api-branch-name: ${{ inputs.APIBranchName }}
      frontend-branch-name: ${{ inputs.FrontBranchName }}
      output-path: ${{ inputs.OutputPath }}
      internal-build: ${{ inputs.InternalBuild }}
      version-number: ${{ inputs.VersionNumber }}
  
  build_macos:
    if: ${{ inputs.Platform }} == 'macos'
    uses: ./.github/workflows/build-macos-installer.yml
    with: 
      api-branch-name: ${{ inputs.APIBranchName }}
      frontend-branch-name: ${{ inputs.FrontBranchName }}
      output-path: ${{ inputs.OutputPath }}
      internal-build: ${{ inputs.InternalBuild }}
      version-number: ${{ inputs.VersionNumber }}



